site_name: Python
site_url: https://salvasevero.github.io/python/
use_directory_urls: false

nav:
  - "UD1."

theme:
  language: es
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo día
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo noche
  logo: imagenes/logofp.png
  features:
    - header.autohide
    - toc.integrate
    - navigation.indexes
    - content.code.copy
#    - navigation.top

extra_css:
  - css/extra.css

plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True

markdown_extensions:
  - attr_list
  - def_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight:
      linenums: false
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 2

copyright: Salvador Serrano Pérez - Licencia CC BY-NC-SA